import DefaultSearchDialog from "@/components/default-search-dialog";
import { DocsLayoutClient } from "@/components/docs-layout-client";
import { ExtraNavLinks } from "@/components/extra-nav-links";
import { ServicePrimaryColor } from "@/components/service-primary-color";
import { ServiceVersionSwitcher } from "@/components/service-version-switcher";
import { baseOptions } from "@/lib/layout.shared";
import { buildAliasTree } from "@/lib/page-tree";
import { getServiceVersionOptions } from "@/lib/service-version-options";
import { getSource } from "@/lib/source";
import { RootProvider } from "fumadocs-ui/provider/next";
import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import { headers } from "next/headers";
import type { CSSProperties } from "react";
import "./globals.css";

const fontSans = Noto_Sans({ variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const requestHeaders = await headers();
  const [source, serviceVersionOptions] = await Promise.all([
    getSource(),
    getServiceVersionOptions(),
  ]);
  const serviceSlug = requestHeaders.get("x-service-slug");
  const servicePrimaryColor = serviceVersionOptions.services
    .find((service) => service.slug === serviceSlug)
    ?.primaryColor?.trim();
  const htmlStyle: CSSProperties | undefined = servicePrimaryColor
    ? ({
        "--primary": servicePrimaryColor,
        "--accent": servicePrimaryColor,
        "--sidebar-primary": servicePrimaryColor,
        "--sidebar-accent": servicePrimaryColor,
      } as CSSProperties)
    : undefined;

  const tree = source.getPageTree();
  const aliasTree = await buildAliasTree(tree);
  const navChildren = (
    <>
      <ServiceVersionSwitcher
        services={serviceVersionOptions.services}
        versionsByService={serviceVersionOptions.versionsByService}
      />
      <ExtraNavLinks />
    </>
  );

  return (
    <html
      lang="en"
      className={fontSans.variable}
      style={htmlStyle}
      suppressHydrationWarning
    >
      <body className="flex min-h-screen flex-col font-sans antialiased">
        <RootProvider search={{ SearchDialog: DefaultSearchDialog }}>
          <ServicePrimaryColor services={serviceVersionOptions.services} />
          <DocsLayoutClient
            tree={tree}
            aliasTree={aliasTree}
            {...baseOptions({ navChildren })}
          >
            {children}
          </DocsLayoutClient>
        </RootProvider>
      </body>
    </html>
  );
}
