import type { Metadata } from "next";
import { RootProvider } from "fumadocs-ui/provider/next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

const fontSans = Noto_Sans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`flex flex-col min-h-screen antialiased font-sans ${fontSans.variable}`}
      >
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
