/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    docVersions: DocVersion;
    docPageGroups: DocPageGroup;
    docPages: DocPage;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    docVersions: DocVersionsSelect<false> | DocVersionsSelect<true>;
    docPageGroups: DocPageGroupsSelect<false> | DocPageGroupsSelect<true>;
    docPages: DocPagesSelect<false> | DocPagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    docsSettings: DocsSetting;
  };
  globalsSelect: {
    docsSettings: DocsSettingsSelect<false> | DocsSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('writer' | 'editor' | 'admin')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * URL prefix for this service (e.g. "api", "cli").
   */
  slug: string;
  /**
   * Short summary shown in the docs service selector. Keep this concise (1-2 lines).
   */
  description: string;
  /**
   * Icon used in the docs service selector.
   */
  icon?: {
    source?: ('lucide' | 'custom') | null;
    /**
     * Search the Lucide icon library by name.
     */
    lucide?:
      | (
          | 'AArrowDown'
          | 'AArrowUp'
          | 'Accessibility'
          | 'Activity'
          | 'Airplay'
          | 'AirVent'
          | 'ALargeSmall'
          | 'AlarmClock'
          | 'AlarmClockCheck'
          | 'AlarmClockMinus'
          | 'AlarmClockOff'
          | 'AlarmClockPlus'
          | 'AlarmSmoke'
          | 'Album'
          | 'AlignCenterHorizontal'
          | 'AlignCenterVertical'
          | 'AlignEndHorizontal'
          | 'AlignEndVertical'
          | 'AlignHorizontalDistributeCenter'
          | 'AlignHorizontalDistributeEnd'
          | 'AlignHorizontalDistributeStart'
          | 'AlignHorizontalJustifyCenter'
          | 'AlignHorizontalJustifyEnd'
          | 'AlignHorizontalJustifyStart'
          | 'AlignHorizontalSpaceAround'
          | 'AlignHorizontalSpaceBetween'
          | 'AlignStartHorizontal'
          | 'AlignStartVertical'
          | 'AlignVerticalDistributeCenter'
          | 'AlignVerticalDistributeEnd'
          | 'AlignVerticalDistributeStart'
          | 'AlignVerticalJustifyCenter'
          | 'AlignVerticalJustifyEnd'
          | 'AlignVerticalJustifyStart'
          | 'AlignVerticalSpaceAround'
          | 'AlignVerticalSpaceBetween'
          | 'Ambulance'
          | 'Ampersand'
          | 'Ampersands'
          | 'Amphora'
          | 'Anchor'
          | 'Angry'
          | 'Annoyed'
          | 'Antenna'
          | 'Anvil'
          | 'Aperture'
          | 'Apple'
          | 'AppWindow'
          | 'AppWindowMac'
          | 'Archive'
          | 'ArchiveRestore'
          | 'ArchiveX'
          | 'Armchair'
          | 'ArrowBigDown'
          | 'ArrowBigDownDash'
          | 'ArrowBigLeft'
          | 'ArrowBigLeftDash'
          | 'ArrowBigRight'
          | 'ArrowBigRightDash'
          | 'ArrowBigUp'
          | 'ArrowBigUpDash'
          | 'ArrowDown'
          | 'ArrowDown01'
          | 'ArrowDown10'
          | 'ArrowDownAZ'
          | 'ArrowDownFromLine'
          | 'ArrowDownLeft'
          | 'ArrowDownNarrowWide'
          | 'ArrowDownRight'
          | 'ArrowDownToDot'
          | 'ArrowDownToLine'
          | 'ArrowDownUp'
          | 'ArrowDownWideNarrow'
          | 'ArrowDownZA'
          | 'ArrowLeft'
          | 'ArrowLeftFromLine'
          | 'ArrowLeftRight'
          | 'ArrowLeftToLine'
          | 'ArrowRight'
          | 'ArrowRightFromLine'
          | 'ArrowRightLeft'
          | 'ArrowRightToLine'
          | 'ArrowsUpFromLine'
          | 'ArrowUp'
          | 'ArrowUp01'
          | 'ArrowUp10'
          | 'ArrowUpAZ'
          | 'ArrowUpDown'
          | 'ArrowUpFromDot'
          | 'ArrowUpFromLine'
          | 'ArrowUpLeft'
          | 'ArrowUpNarrowWide'
          | 'ArrowUpRight'
          | 'ArrowUpToLine'
          | 'ArrowUpWideNarrow'
          | 'ArrowUpZA'
          | 'Asterisk'
          | 'Atom'
          | 'AtSign'
          | 'AudioLines'
          | 'AudioWaveform'
          | 'Award'
          | 'Axe'
          | 'Axis3d'
          | 'Baby'
          | 'Backpack'
          | 'Badge'
          | 'BadgeAlert'
          | 'BadgeCent'
          | 'BadgeCheck'
          | 'BadgeDollarSign'
          | 'BadgeEuro'
          | 'BadgeIndianRupee'
          | 'BadgeInfo'
          | 'BadgeJapaneseYen'
          | 'BadgeMinus'
          | 'BadgePercent'
          | 'BadgePlus'
          | 'BadgePoundSterling'
          | 'BadgeQuestionMark'
          | 'BadgeRussianRuble'
          | 'BadgeSwissFranc'
          | 'BadgeTurkishLira'
          | 'BadgeX'
          | 'BaggageClaim'
          | 'Balloon'
          | 'Ban'
          | 'Banana'
          | 'Bandage'
          | 'Banknote'
          | 'BanknoteArrowDown'
          | 'BanknoteArrowUp'
          | 'BanknoteX'
          | 'Barcode'
          | 'Barrel'
          | 'Baseline'
          | 'Bath'
          | 'Battery'
          | 'BatteryCharging'
          | 'BatteryFull'
          | 'BatteryLow'
          | 'BatteryMedium'
          | 'BatteryPlus'
          | 'BatteryWarning'
          | 'Beaker'
          | 'Bean'
          | 'BeanOff'
          | 'Bed'
          | 'BedDouble'
          | 'BedSingle'
          | 'Beef'
          | 'Beer'
          | 'BeerOff'
          | 'Bell'
          | 'BellDot'
          | 'BellElectric'
          | 'BellMinus'
          | 'BellOff'
          | 'BellPlus'
          | 'BellRing'
          | 'BetweenHorizontalEnd'
          | 'BetweenHorizontalStart'
          | 'BetweenVerticalEnd'
          | 'BetweenVerticalStart'
          | 'BicepsFlexed'
          | 'Bike'
          | 'Binary'
          | 'Binoculars'
          | 'Biohazard'
          | 'Bird'
          | 'Birdhouse'
          | 'Bitcoin'
          | 'Blend'
          | 'Blinds'
          | 'Blocks'
          | 'Bluetooth'
          | 'BluetoothConnected'
          | 'BluetoothOff'
          | 'BluetoothSearching'
          | 'Bold'
          | 'Bolt'
          | 'Bomb'
          | 'Bone'
          | 'Book'
          | 'BookA'
          | 'BookAlert'
          | 'BookAudio'
          | 'BookCheck'
          | 'BookCopy'
          | 'BookDashed'
          | 'BookDown'
          | 'BookHeadphones'
          | 'BookHeart'
          | 'BookImage'
          | 'BookKey'
          | 'BookLock'
          | 'Bookmark'
          | 'BookmarkCheck'
          | 'BookMarked'
          | 'BookmarkMinus'
          | 'BookmarkPlus'
          | 'BookmarkX'
          | 'BookMinus'
          | 'BookOpen'
          | 'BookOpenCheck'
          | 'BookOpenText'
          | 'BookPlus'
          | 'BookSearch'
          | 'BookText'
          | 'BookType'
          | 'BookUp'
          | 'BookUp2'
          | 'BookUser'
          | 'BookX'
          | 'BoomBox'
          | 'Bot'
          | 'BotMessageSquare'
          | 'BotOff'
          | 'BottleWine'
          | 'BowArrow'
          | 'Box'
          | 'Boxes'
          | 'Braces'
          | 'Brackets'
          | 'Brain'
          | 'BrainCircuit'
          | 'BrainCog'
          | 'BrickWall'
          | 'BrickWallFire'
          | 'BrickWallShield'
          | 'Briefcase'
          | 'BriefcaseBusiness'
          | 'BriefcaseConveyorBelt'
          | 'BriefcaseMedical'
          | 'BringToFront'
          | 'Brush'
          | 'BrushCleaning'
          | 'Bubbles'
          | 'Bug'
          | 'BugOff'
          | 'BugPlay'
          | 'Building'
          | 'Building2'
          | 'Bus'
          | 'BusFront'
          | 'Cable'
          | 'CableCar'
          | 'Cake'
          | 'CakeSlice'
          | 'Calculator'
          | 'Calendar'
          | 'Calendar1'
          | 'CalendarArrowDown'
          | 'CalendarArrowUp'
          | 'CalendarCheck'
          | 'CalendarCheck2'
          | 'CalendarClock'
          | 'CalendarCog'
          | 'CalendarDays'
          | 'CalendarFold'
          | 'CalendarHeart'
          | 'CalendarMinus'
          | 'CalendarMinus2'
          | 'CalendarOff'
          | 'CalendarPlus'
          | 'CalendarPlus2'
          | 'CalendarRange'
          | 'Calendars'
          | 'CalendarSearch'
          | 'CalendarSync'
          | 'CalendarX'
          | 'CalendarX2'
          | 'Camera'
          | 'CameraOff'
          | 'Candy'
          | 'CandyCane'
          | 'CandyOff'
          | 'Cannabis'
          | 'CannabisOff'
          | 'Captions'
          | 'CaptionsOff'
          | 'Car'
          | 'Caravan'
          | 'CardSim'
          | 'CarFront'
          | 'Carrot'
          | 'CarTaxiFront'
          | 'CaseLower'
          | 'CaseSensitive'
          | 'CaseUpper'
          | 'CassetteTape'
          | 'Cast'
          | 'Castle'
          | 'Cat'
          | 'Cctv'
          | 'ChartArea'
          | 'ChartBar'
          | 'ChartBarBig'
          | 'ChartBarDecreasing'
          | 'ChartBarIncreasing'
          | 'ChartBarStacked'
          | 'ChartCandlestick'
          | 'ChartColumn'
          | 'ChartColumnBig'
          | 'ChartColumnDecreasing'
          | 'ChartColumnIncreasing'
          | 'ChartColumnStacked'
          | 'ChartGantt'
          | 'ChartLine'
          | 'ChartNetwork'
          | 'ChartNoAxesColumn'
          | 'ChartNoAxesColumnDecreasing'
          | 'ChartNoAxesColumnIncreasing'
          | 'ChartNoAxesCombined'
          | 'ChartNoAxesGantt'
          | 'ChartPie'
          | 'ChartScatter'
          | 'ChartSpline'
          | 'Check'
          | 'CheckCheck'
          | 'CheckLine'
          | 'ChefHat'
          | 'Cherry'
          | 'ChessBishop'
          | 'ChessKing'
          | 'ChessKnight'
          | 'ChessPawn'
          | 'ChessQueen'
          | 'ChessRook'
          | 'ChevronDown'
          | 'ChevronFirst'
          | 'ChevronLast'
          | 'ChevronLeft'
          | 'ChevronRight'
          | 'ChevronsDown'
          | 'ChevronsDownUp'
          | 'ChevronsLeft'
          | 'ChevronsLeftRight'
          | 'ChevronsLeftRightEllipsis'
          | 'ChevronsRight'
          | 'ChevronsRightLeft'
          | 'ChevronsUp'
          | 'ChevronsUpDown'
          | 'ChevronUp'
          | 'Chromium'
          | 'Church'
          | 'Cigarette'
          | 'CigaretteOff'
          | 'Circle'
          | 'CircleAlert'
          | 'CircleArrowDown'
          | 'CircleArrowLeft'
          | 'CircleArrowOutDownLeft'
          | 'CircleArrowOutDownRight'
          | 'CircleArrowOutUpLeft'
          | 'CircleArrowOutUpRight'
          | 'CircleArrowRight'
          | 'CircleArrowUp'
          | 'CircleCheck'
          | 'CircleCheckBig'
          | 'CircleChevronDown'
          | 'CircleChevronLeft'
          | 'CircleChevronRight'
          | 'CircleChevronUp'
          | 'CircleDashed'
          | 'CircleDivide'
          | 'CircleDollarSign'
          | 'CircleDot'
          | 'CircleDotDashed'
          | 'CircleEllipsis'
          | 'CircleEqual'
          | 'CircleFadingArrowUp'
          | 'CircleFadingPlus'
          | 'CircleGauge'
          | 'CircleMinus'
          | 'CircleOff'
          | 'CircleParking'
          | 'CircleParkingOff'
          | 'CirclePause'
          | 'CirclePercent'
          | 'CirclePile'
          | 'CirclePlay'
          | 'CirclePlus'
          | 'CirclePoundSterling'
          | 'CirclePower'
          | 'CircleQuestionMark'
          | 'CircleSlash'
          | 'CircleSlash2'
          | 'CircleSmall'
          | 'CircleStar'
          | 'CircleStop'
          | 'CircleUser'
          | 'CircleUserRound'
          | 'CircleX'
          | 'CircuitBoard'
          | 'Citrus'
          | 'Clapperboard'
          | 'Clipboard'
          | 'ClipboardCheck'
          | 'ClipboardClock'
          | 'ClipboardCopy'
          | 'ClipboardList'
          | 'ClipboardMinus'
          | 'ClipboardPaste'
          | 'ClipboardPen'
          | 'ClipboardPenLine'
          | 'ClipboardPlus'
          | 'ClipboardType'
          | 'ClipboardX'
          | 'Clock'
          | 'Clock1'
          | 'Clock10'
          | 'Clock11'
          | 'Clock12'
          | 'Clock2'
          | 'Clock3'
          | 'Clock4'
          | 'Clock5'
          | 'Clock6'
          | 'Clock7'
          | 'Clock8'
          | 'Clock9'
          | 'ClockAlert'
          | 'ClockArrowDown'
          | 'ClockArrowUp'
          | 'ClockCheck'
          | 'ClockFading'
          | 'ClockPlus'
          | 'ClosedCaption'
          | 'Cloud'
          | 'CloudAlert'
          | 'CloudBackup'
          | 'CloudCheck'
          | 'CloudCog'
          | 'CloudDownload'
          | 'CloudDrizzle'
          | 'CloudFog'
          | 'CloudHail'
          | 'CloudLightning'
          | 'CloudMoon'
          | 'CloudMoonRain'
          | 'CloudOff'
          | 'CloudRain'
          | 'CloudRainWind'
          | 'CloudSnow'
          | 'CloudSun'
          | 'CloudSunRain'
          | 'CloudSync'
          | 'CloudUpload'
          | 'Cloudy'
          | 'Clover'
          | 'Club'
          | 'Code'
          | 'Codepen'
          | 'Codesandbox'
          | 'CodeXml'
          | 'Coffee'
          | 'Cog'
          | 'Coins'
          | 'Columns2'
          | 'Columns3'
          | 'Columns3Cog'
          | 'Columns4'
          | 'Combine'
          | 'Command'
          | 'Compass'
          | 'Component'
          | 'Computer'
          | 'ConciergeBell'
          | 'Cone'
          | 'Construction'
          | 'Contact'
          | 'ContactRound'
          | 'Container'
          | 'Contrast'
          | 'Cookie'
          | 'CookingPot'
          | 'Copy'
          | 'CopyCheck'
          | 'Copyleft'
          | 'CopyMinus'
          | 'CopyPlus'
          | 'Copyright'
          | 'CopySlash'
          | 'CopyX'
          | 'CornerDownLeft'
          | 'CornerDownRight'
          | 'CornerLeftDown'
          | 'CornerLeftUp'
          | 'CornerRightDown'
          | 'CornerRightUp'
          | 'CornerUpLeft'
          | 'CornerUpRight'
          | 'Cpu'
          | 'CreativeCommons'
          | 'CreditCard'
          | 'Croissant'
          | 'Crop'
          | 'Cross'
          | 'Crosshair'
          | 'Crown'
          | 'Cuboid'
          | 'CupSoda'
          | 'Currency'
          | 'Cylinder'
          | 'Dam'
          | 'Database'
          | 'DatabaseBackup'
          | 'DatabaseZap'
          | 'DecimalsArrowLeft'
          | 'DecimalsArrowRight'
          | 'Delete'
          | 'Dessert'
          | 'Diameter'
          | 'Diamond'
          | 'DiamondMinus'
          | 'DiamondPercent'
          | 'DiamondPlus'
          | 'Dice1'
          | 'Dice2'
          | 'Dice3'
          | 'Dice4'
          | 'Dice5'
          | 'Dice6'
          | 'Dices'
          | 'Diff'
          | 'Disc'
          | 'Disc2'
          | 'Disc3'
          | 'DiscAlbum'
          | 'Divide'
          | 'Dna'
          | 'DnaOff'
          | 'Dock'
          | 'Dog'
          | 'DollarSign'
          | 'Donut'
          | 'DoorClosed'
          | 'DoorClosedLocked'
          | 'DoorOpen'
          | 'Dot'
          | 'Download'
          | 'DraftingCompass'
          | 'Drama'
          | 'Dribbble'
          | 'Drill'
          | 'Drone'
          | 'Droplet'
          | 'DropletOff'
          | 'Droplets'
          | 'Drum'
          | 'Drumstick'
          | 'Dumbbell'
          | 'Ear'
          | 'EarOff'
          | 'Earth'
          | 'EarthLock'
          | 'Eclipse'
          | 'Egg'
          | 'EggFried'
          | 'EggOff'
          | 'Ellipsis'
          | 'EllipsisVertical'
          | 'Equal'
          | 'EqualApproximately'
          | 'EqualNot'
          | 'Eraser'
          | 'EthernetPort'
          | 'Euro'
          | 'EvCharger'
          | 'Expand'
          | 'ExternalLink'
          | 'Eye'
          | 'EyeClosed'
          | 'EyeOff'
          | 'Facebook'
          | 'Factory'
          | 'Fan'
          | 'FastForward'
          | 'Feather'
          | 'Fence'
          | 'FerrisWheel'
          | 'Figma'
          | 'File'
          | 'FileArchive'
          | 'FileAxis3d'
          | 'FileBadge'
          | 'FileBox'
          | 'FileBraces'
          | 'FileBracesCorner'
          | 'FileChartColumn'
          | 'FileChartColumnIncreasing'
          | 'FileChartLine'
          | 'FileChartPie'
          | 'FileCheck'
          | 'FileCheckCorner'
          | 'FileClock'
          | 'FileCode'
          | 'FileCodeCorner'
          | 'FileCog'
          | 'FileDiff'
          | 'FileDigit'
          | 'FileDown'
          | 'FileExclamationPoint'
          | 'FileHeadphone'
          | 'FileHeart'
          | 'FileImage'
          | 'FileInput'
          | 'FileKey'
          | 'FileLock'
          | 'FileMinus'
          | 'FileMinusCorner'
          | 'FileMusic'
          | 'FileOutput'
          | 'FilePen'
          | 'FilePenLine'
          | 'FilePlay'
          | 'FilePlus'
          | 'FilePlusCorner'
          | 'FileQuestionMark'
          | 'Files'
          | 'FileScan'
          | 'FileSearch'
          | 'FileSearchCorner'
          | 'FileSignal'
          | 'FileSliders'
          | 'FileSpreadsheet'
          | 'FileStack'
          | 'FileSymlink'
          | 'FileTerminal'
          | 'FileText'
          | 'FileType'
          | 'FileTypeCorner'
          | 'FileUp'
          | 'FileUser'
          | 'FileVideoCamera'
          | 'FileVolume'
          | 'FileX'
          | 'FileXCorner'
          | 'Film'
          | 'FingerprintPattern'
          | 'FireExtinguisher'
          | 'Fish'
          | 'FishingHook'
          | 'FishOff'
          | 'FishSymbol'
          | 'Flag'
          | 'FlagOff'
          | 'FlagTriangleLeft'
          | 'FlagTriangleRight'
          | 'Flame'
          | 'FlameKindling'
          | 'Flashlight'
          | 'FlashlightOff'
          | 'FlaskConical'
          | 'FlaskConicalOff'
          | 'FlaskRound'
          | 'FlipHorizontal'
          | 'FlipHorizontal2'
          | 'FlipVertical'
          | 'FlipVertical2'
          | 'Flower'
          | 'Flower2'
          | 'Focus'
          | 'Folder'
          | 'FolderArchive'
          | 'FolderCheck'
          | 'FolderClock'
          | 'FolderClosed'
          | 'FolderCode'
          | 'FolderCog'
          | 'FolderDot'
          | 'FolderDown'
          | 'FolderGit'
          | 'FolderGit2'
          | 'FolderHeart'
          | 'FolderInput'
          | 'FolderKanban'
          | 'FolderKey'
          | 'FolderLock'
          | 'FolderMinus'
          | 'FolderOpen'
          | 'FolderOpenDot'
          | 'FolderOutput'
          | 'FolderPen'
          | 'FolderPlus'
          | 'FolderRoot'
          | 'Folders'
          | 'FolderSearch'
          | 'FolderSearch2'
          | 'FolderSymlink'
          | 'FolderSync'
          | 'FolderTree'
          | 'FolderUp'
          | 'FolderX'
          | 'FoldHorizontal'
          | 'FoldVertical'
          | 'Footprints'
          | 'Forklift'
          | 'Form'
          | 'Forward'
          | 'Frame'
          | 'Framer'
          | 'Frown'
          | 'Fuel'
          | 'Fullscreen'
          | 'Funnel'
          | 'FunnelPlus'
          | 'FunnelX'
          | 'GalleryHorizontal'
          | 'GalleryHorizontalEnd'
          | 'GalleryThumbnails'
          | 'GalleryVertical'
          | 'GalleryVerticalEnd'
          | 'Gamepad'
          | 'Gamepad2'
          | 'GamepadDirectional'
          | 'Gauge'
          | 'Gavel'
          | 'Gem'
          | 'GeorgianLari'
          | 'Ghost'
          | 'Gift'
          | 'GitBranch'
          | 'GitBranchMinus'
          | 'GitBranchPlus'
          | 'GitCommitHorizontal'
          | 'GitCommitVertical'
          | 'GitCompare'
          | 'GitCompareArrows'
          | 'GitFork'
          | 'GitGraph'
          | 'Github'
          | 'Gitlab'
          | 'GitMerge'
          | 'GitPullRequest'
          | 'GitPullRequestArrow'
          | 'GitPullRequestClosed'
          | 'GitPullRequestCreate'
          | 'GitPullRequestCreateArrow'
          | 'GitPullRequestDraft'
          | 'Glasses'
          | 'GlassWater'
          | 'Globe'
          | 'GlobeLock'
          | 'GlobeX'
          | 'Goal'
          | 'Gpu'
          | 'GraduationCap'
          | 'Grape'
          | 'Grid2x2'
          | 'Grid2x2Check'
          | 'Grid2x2Plus'
          | 'Grid2x2X'
          | 'Grid3x2'
          | 'Grid3x3'
          | 'Grip'
          | 'GripHorizontal'
          | 'GripVertical'
          | 'Group'
          | 'Guitar'
          | 'Ham'
          | 'Hamburger'
          | 'Hammer'
          | 'Hand'
          | 'Handbag'
          | 'HandCoins'
          | 'HandFist'
          | 'HandGrab'
          | 'HandHeart'
          | 'HandHelping'
          | 'HandMetal'
          | 'HandPlatter'
          | 'Handshake'
          | 'HardDrive'
          | 'HardDriveDownload'
          | 'HardDriveUpload'
          | 'HardHat'
          | 'Hash'
          | 'HatGlasses'
          | 'Haze'
          | 'Hd'
          | 'HdmiPort'
          | 'Heading'
          | 'Heading1'
          | 'Heading2'
          | 'Heading3'
          | 'Heading4'
          | 'Heading5'
          | 'Heading6'
          | 'HeadphoneOff'
          | 'Headphones'
          | 'Headset'
          | 'Heart'
          | 'HeartCrack'
          | 'HeartHandshake'
          | 'HeartMinus'
          | 'HeartOff'
          | 'HeartPlus'
          | 'HeartPulse'
          | 'Heater'
          | 'Helicopter'
          | 'Hexagon'
          | 'Highlighter'
          | 'History'
          | 'Hop'
          | 'HopOff'
          | 'Hospital'
          | 'Hotel'
          | 'Hourglass'
          | 'House'
          | 'HouseHeart'
          | 'HousePlug'
          | 'HousePlus'
          | 'HouseWifi'
          | 'IceCreamBowl'
          | 'IceCreamCone'
          | 'IdCard'
          | 'IdCardLanyard'
          | 'Image'
          | 'ImageDown'
          | 'ImageMinus'
          | 'ImageOff'
          | 'ImagePlay'
          | 'ImagePlus'
          | 'Images'
          | 'ImageUp'
          | 'ImageUpscale'
          | 'Import'
          | 'Inbox'
          | 'IndianRupee'
          | 'Infinity'
          | 'Info'
          | 'InspectionPanel'
          | 'Instagram'
          | 'Italic'
          | 'IterationCcw'
          | 'IterationCw'
          | 'JapaneseYen'
          | 'Joystick'
          | 'Kanban'
          | 'Kayak'
          | 'Key'
          | 'Keyboard'
          | 'KeyboardMusic'
          | 'KeyboardOff'
          | 'KeyRound'
          | 'KeySquare'
          | 'Lamp'
          | 'LampCeiling'
          | 'LampDesk'
          | 'LampFloor'
          | 'LampWallDown'
          | 'LampWallUp'
          | 'Landmark'
          | 'LandPlot'
          | 'Languages'
          | 'Laptop'
          | 'LaptopMinimal'
          | 'LaptopMinimalCheck'
          | 'Lasso'
          | 'LassoSelect'
          | 'Laugh'
          | 'Layers'
          | 'Layers2'
          | 'LayersPlus'
          | 'LayoutDashboard'
          | 'LayoutGrid'
          | 'LayoutList'
          | 'LayoutPanelLeft'
          | 'LayoutPanelTop'
          | 'LayoutTemplate'
          | 'Leaf'
          | 'LeafyGreen'
          | 'Lectern'
          | 'Library'
          | 'LibraryBig'
          | 'LifeBuoy'
          | 'Ligature'
          | 'Lightbulb'
          | 'LightbulbOff'
          | 'LineSquiggle'
          | 'Link'
          | 'Link2'
          | 'Link2Off'
          | 'Linkedin'
          | 'List'
          | 'ListCheck'
          | 'ListChecks'
          | 'ListChevronsDownUp'
          | 'ListChevronsUpDown'
          | 'ListCollapse'
          | 'ListEnd'
          | 'ListFilter'
          | 'ListFilterPlus'
          | 'ListIndentDecrease'
          | 'ListIndentIncrease'
          | 'ListMinus'
          | 'ListMusic'
          | 'ListOrdered'
          | 'ListPlus'
          | 'ListRestart'
          | 'ListStart'
          | 'ListTodo'
          | 'ListTree'
          | 'ListVideo'
          | 'ListX'
          | 'Loader'
          | 'LoaderCircle'
          | 'LoaderPinwheel'
          | 'Locate'
          | 'LocateFixed'
          | 'LocateOff'
          | 'Lock'
          | 'LockKeyhole'
          | 'LockKeyholeOpen'
          | 'LockOpen'
          | 'LogIn'
          | 'LogOut'
          | 'Logs'
          | 'Lollipop'
          | 'Luggage'
          | 'Magnet'
          | 'Mail'
          | 'Mailbox'
          | 'MailCheck'
          | 'MailMinus'
          | 'MailOpen'
          | 'MailPlus'
          | 'MailQuestionMark'
          | 'Mails'
          | 'MailSearch'
          | 'MailWarning'
          | 'MailX'
          | 'Map'
          | 'MapMinus'
          | 'MapPin'
          | 'MapPinCheck'
          | 'MapPinCheckInside'
          | 'MapPinHouse'
          | 'MapPinMinus'
          | 'MapPinMinusInside'
          | 'MapPinned'
          | 'MapPinOff'
          | 'MapPinPen'
          | 'MapPinPlus'
          | 'MapPinPlusInside'
          | 'MapPinX'
          | 'MapPinXInside'
          | 'MapPlus'
          | 'Mars'
          | 'MarsStroke'
          | 'Martini'
          | 'Maximize'
          | 'Maximize2'
          | 'Medal'
          | 'Megaphone'
          | 'MegaphoneOff'
          | 'Meh'
          | 'MemoryStick'
          | 'Menu'
          | 'Merge'
          | 'MessageCircle'
          | 'MessageCircleCode'
          | 'MessageCircleDashed'
          | 'MessageCircleHeart'
          | 'MessageCircleMore'
          | 'MessageCircleOff'
          | 'MessageCirclePlus'
          | 'MessageCircleQuestionMark'
          | 'MessageCircleReply'
          | 'MessageCircleWarning'
          | 'MessageCircleX'
          | 'MessageSquare'
          | 'MessageSquareCode'
          | 'MessageSquareDashed'
          | 'MessageSquareDiff'
          | 'MessageSquareDot'
          | 'MessageSquareHeart'
          | 'MessageSquareLock'
          | 'MessageSquareMore'
          | 'MessageSquareOff'
          | 'MessageSquarePlus'
          | 'MessageSquareQuote'
          | 'MessageSquareReply'
          | 'MessageSquareShare'
          | 'MessageSquareText'
          | 'MessageSquareWarning'
          | 'MessageSquareX'
          | 'MessagesSquare'
          | 'Mic'
          | 'MicOff'
          | 'Microchip'
          | 'Microscope'
          | 'Microwave'
          | 'MicVocal'
          | 'Milestone'
          | 'Milk'
          | 'MilkOff'
          | 'Minimize'
          | 'Minimize2'
          | 'Minus'
          | 'Monitor'
          | 'MonitorCheck'
          | 'MonitorCloud'
          | 'MonitorCog'
          | 'MonitorDot'
          | 'MonitorDown'
          | 'MonitorOff'
          | 'MonitorPause'
          | 'MonitorPlay'
          | 'MonitorSmartphone'
          | 'MonitorSpeaker'
          | 'MonitorStop'
          | 'MonitorUp'
          | 'MonitorX'
          | 'Moon'
          | 'MoonStar'
          | 'Motorbike'
          | 'Mountain'
          | 'MountainSnow'
          | 'Mouse'
          | 'MouseOff'
          | 'MousePointer'
          | 'MousePointer2'
          | 'MousePointer2Off'
          | 'MousePointerBan'
          | 'MousePointerClick'
          | 'Move'
          | 'Move3d'
          | 'MoveDiagonal'
          | 'MoveDiagonal2'
          | 'MoveDown'
          | 'MoveDownLeft'
          | 'MoveDownRight'
          | 'MoveHorizontal'
          | 'MoveLeft'
          | 'MoveRight'
          | 'MoveUp'
          | 'MoveUpLeft'
          | 'MoveUpRight'
          | 'MoveVertical'
          | 'Music'
          | 'Music2'
          | 'Music3'
          | 'Music4'
          | 'Navigation'
          | 'Navigation2'
          | 'Navigation2Off'
          | 'NavigationOff'
          | 'Network'
          | 'Newspaper'
          | 'Nfc'
          | 'NonBinary'
          | 'Notebook'
          | 'NotebookPen'
          | 'NotebookTabs'
          | 'NotebookText'
          | 'NotepadText'
          | 'NotepadTextDashed'
          | 'Nut'
          | 'NutOff'
          | 'Octagon'
          | 'OctagonAlert'
          | 'OctagonMinus'
          | 'OctagonPause'
          | 'OctagonX'
          | 'Omega'
          | 'Option'
          | 'Orbit'
          | 'Origami'
          | 'Package'
          | 'Package2'
          | 'PackageCheck'
          | 'PackageMinus'
          | 'PackageOpen'
          | 'PackagePlus'
          | 'PackageSearch'
          | 'PackageX'
          | 'Paintbrush'
          | 'PaintbrushVertical'
          | 'PaintBucket'
          | 'PaintRoller'
          | 'Palette'
          | 'Panda'
          | 'PanelBottom'
          | 'PanelBottomClose'
          | 'PanelBottomDashed'
          | 'PanelBottomOpen'
          | 'PanelLeft'
          | 'PanelLeftClose'
          | 'PanelLeftDashed'
          | 'PanelLeftOpen'
          | 'PanelLeftRightDashed'
          | 'PanelRight'
          | 'PanelRightClose'
          | 'PanelRightDashed'
          | 'PanelRightOpen'
          | 'PanelsLeftBottom'
          | 'PanelsRightBottom'
          | 'PanelsTopLeft'
          | 'PanelTop'
          | 'PanelTopBottomDashed'
          | 'PanelTopClose'
          | 'PanelTopDashed'
          | 'PanelTopOpen'
          | 'Paperclip'
          | 'Parentheses'
          | 'ParkingMeter'
          | 'PartyPopper'
          | 'Pause'
          | 'PawPrint'
          | 'PcCase'
          | 'Pen'
          | 'Pencil'
          | 'PencilLine'
          | 'PencilOff'
          | 'PencilRuler'
          | 'PenLine'
          | 'PenOff'
          | 'Pentagon'
          | 'PenTool'
          | 'Percent'
          | 'PersonStanding'
          | 'PhilippinePeso'
          | 'Phone'
          | 'PhoneCall'
          | 'PhoneForwarded'
          | 'PhoneIncoming'
          | 'PhoneMissed'
          | 'PhoneOff'
          | 'PhoneOutgoing'
          | 'Pi'
          | 'Piano'
          | 'Pickaxe'
          | 'PictureInPicture'
          | 'PictureInPicture2'
          | 'PiggyBank'
          | 'Pilcrow'
          | 'PilcrowLeft'
          | 'PilcrowRight'
          | 'Pill'
          | 'PillBottle'
          | 'Pin'
          | 'PinOff'
          | 'Pipette'
          | 'Pizza'
          | 'Plane'
          | 'PlaneLanding'
          | 'PlaneTakeoff'
          | 'Play'
          | 'Plug'
          | 'Plug2'
          | 'PlugZap'
          | 'Plus'
          | 'Pocket'
          | 'PocketKnife'
          | 'Podcast'
          | 'Pointer'
          | 'PointerOff'
          | 'Popcorn'
          | 'Popsicle'
          | 'PoundSterling'
          | 'Power'
          | 'PowerOff'
          | 'Presentation'
          | 'Printer'
          | 'PrinterCheck'
          | 'PrinterX'
          | 'Projector'
          | 'Proportions'
          | 'Puzzle'
          | 'Pyramid'
          | 'QrCode'
          | 'Quote'
          | 'Rabbit'
          | 'Radar'
          | 'Radiation'
          | 'Radical'
          | 'Radio'
          | 'RadioReceiver'
          | 'RadioTower'
          | 'Radius'
          | 'RailSymbol'
          | 'Rainbow'
          | 'Rat'
          | 'Ratio'
          | 'Receipt'
          | 'ReceiptCent'
          | 'ReceiptEuro'
          | 'ReceiptIndianRupee'
          | 'ReceiptJapaneseYen'
          | 'ReceiptPoundSterling'
          | 'ReceiptRussianRuble'
          | 'ReceiptSwissFranc'
          | 'ReceiptText'
          | 'ReceiptTurkishLira'
          | 'RectangleCircle'
          | 'RectangleEllipsis'
          | 'RectangleGoggles'
          | 'RectangleHorizontal'
          | 'RectangleVertical'
          | 'Recycle'
          | 'Redo'
          | 'Redo2'
          | 'RedoDot'
          | 'RefreshCcw'
          | 'RefreshCcwDot'
          | 'RefreshCw'
          | 'RefreshCwOff'
          | 'Refrigerator'
          | 'Regex'
          | 'RemoveFormatting'
          | 'Repeat'
          | 'Repeat1'
          | 'Repeat2'
          | 'Replace'
          | 'ReplaceAll'
          | 'Reply'
          | 'ReplyAll'
          | 'Rewind'
          | 'Ribbon'
          | 'Rocket'
          | 'RockingChair'
          | 'RollerCoaster'
          | 'Rose'
          | 'Rotate3d'
          | 'RotateCcw'
          | 'RotateCcwKey'
          | 'RotateCcwSquare'
          | 'RotateCw'
          | 'RotateCwSquare'
          | 'Route'
          | 'RouteOff'
          | 'Router'
          | 'Rows2'
          | 'Rows3'
          | 'Rows4'
          | 'Rss'
          | 'Ruler'
          | 'RulerDimensionLine'
          | 'RussianRuble'
          | 'Sailboat'
          | 'Salad'
          | 'Sandwich'
          | 'Satellite'
          | 'SatelliteDish'
          | 'SaudiRiyal'
          | 'Save'
          | 'SaveAll'
          | 'SaveOff'
          | 'Scale'
          | 'Scale3d'
          | 'Scaling'
          | 'Scan'
          | 'ScanBarcode'
          | 'ScanEye'
          | 'ScanFace'
          | 'ScanHeart'
          | 'ScanLine'
          | 'ScanQrCode'
          | 'ScanSearch'
          | 'ScanText'
          | 'School'
          | 'Scissors'
          | 'ScissorsLineDashed'
          | 'Scooter'
          | 'ScreenShare'
          | 'ScreenShareOff'
          | 'Scroll'
          | 'ScrollText'
          | 'Search'
          | 'SearchAlert'
          | 'SearchCheck'
          | 'SearchCode'
          | 'SearchSlash'
          | 'SearchX'
          | 'Section'
          | 'Send'
          | 'SendHorizontal'
          | 'SendToBack'
          | 'SeparatorHorizontal'
          | 'SeparatorVertical'
          | 'Server'
          | 'ServerCog'
          | 'ServerCrash'
          | 'ServerOff'
          | 'Settings'
          | 'Settings2'
          | 'Shapes'
          | 'Share'
          | 'Share2'
          | 'Sheet'
          | 'Shell'
          | 'Shield'
          | 'ShieldAlert'
          | 'ShieldBan'
          | 'ShieldCheck'
          | 'ShieldEllipsis'
          | 'ShieldHalf'
          | 'ShieldMinus'
          | 'ShieldOff'
          | 'ShieldPlus'
          | 'ShieldQuestionMark'
          | 'ShieldUser'
          | 'ShieldX'
          | 'Ship'
          | 'ShipWheel'
          | 'Shirt'
          | 'ShoppingBag'
          | 'ShoppingBasket'
          | 'ShoppingCart'
          | 'Shovel'
          | 'ShowerHead'
          | 'Shredder'
          | 'Shrimp'
          | 'Shrink'
          | 'Shrub'
          | 'Shuffle'
          | 'Sigma'
          | 'Signal'
          | 'SignalHigh'
          | 'SignalLow'
          | 'SignalMedium'
          | 'SignalZero'
          | 'Signature'
          | 'Signpost'
          | 'SignpostBig'
          | 'Siren'
          | 'SkipBack'
          | 'SkipForward'
          | 'Skull'
          | 'Slack'
          | 'Slash'
          | 'Slice'
          | 'SlidersHorizontal'
          | 'SlidersVertical'
          | 'Smartphone'
          | 'SmartphoneCharging'
          | 'SmartphoneNfc'
          | 'Smile'
          | 'SmilePlus'
          | 'Snail'
          | 'Snowflake'
          | 'SoapDispenserDroplet'
          | 'Sofa'
          | 'SolarPanel'
          | 'Soup'
          | 'Space'
          | 'Spade'
          | 'Sparkle'
          | 'Sparkles'
          | 'Speaker'
          | 'Speech'
          | 'SpellCheck'
          | 'SpellCheck2'
          | 'Spline'
          | 'SplinePointer'
          | 'Split'
          | 'Spool'
          | 'Spotlight'
          | 'SprayCan'
          | 'Sprout'
          | 'Square'
          | 'SquareActivity'
          | 'SquareArrowDown'
          | 'SquareArrowDownLeft'
          | 'SquareArrowDownRight'
          | 'SquareArrowLeft'
          | 'SquareArrowOutDownLeft'
          | 'SquareArrowOutDownRight'
          | 'SquareArrowOutUpLeft'
          | 'SquareArrowOutUpRight'
          | 'SquareArrowRight'
          | 'SquareArrowUp'
          | 'SquareArrowUpLeft'
          | 'SquareArrowUpRight'
          | 'SquareAsterisk'
          | 'SquareBottomDashedScissors'
          | 'SquareChartGantt'
          | 'SquareCheck'
          | 'SquareCheckBig'
          | 'SquareChevronDown'
          | 'SquareChevronLeft'
          | 'SquareChevronRight'
          | 'SquareChevronUp'
          | 'SquareCode'
          | 'SquareDashed'
          | 'SquareDashedBottom'
          | 'SquareDashedBottomCode'
          | 'SquareDashedKanban'
          | 'SquareDashedMousePointer'
          | 'SquareDashedTopSolid'
          | 'SquareDivide'
          | 'SquareDot'
          | 'SquareEqual'
          | 'SquareFunction'
          | 'SquareKanban'
          | 'SquareLibrary'
          | 'SquareM'
          | 'SquareMenu'
          | 'SquareMinus'
          | 'SquareMousePointer'
          | 'SquareParking'
          | 'SquareParkingOff'
          | 'SquarePause'
          | 'SquarePen'
          | 'SquarePercent'
          | 'SquarePi'
          | 'SquarePilcrow'
          | 'SquarePlay'
          | 'SquarePlus'
          | 'SquarePower'
          | 'SquareRadical'
          | 'SquareRoundCorner'
          | 'SquareScissors'
          | 'SquaresExclude'
          | 'SquareSigma'
          | 'SquaresIntersect'
          | 'SquareSlash'
          | 'SquareSplitHorizontal'
          | 'SquareSplitVertical'
          | 'SquareSquare'
          | 'SquaresSubtract'
          | 'SquareStack'
          | 'SquareStar'
          | 'SquareStop'
          | 'SquaresUnite'
          | 'SquareTerminal'
          | 'SquareUser'
          | 'SquareUserRound'
          | 'SquareX'
          | 'Squircle'
          | 'SquircleDashed'
          | 'Squirrel'
          | 'Stamp'
          | 'Star'
          | 'StarHalf'
          | 'StarOff'
          | 'StepBack'
          | 'StepForward'
          | 'Stethoscope'
          | 'Sticker'
          | 'StickyNote'
          | 'Stone'
          | 'Store'
          | 'StretchHorizontal'
          | 'StretchVertical'
          | 'Strikethrough'
          | 'Subscript'
          | 'Sun'
          | 'SunDim'
          | 'SunMedium'
          | 'SunMoon'
          | 'Sunrise'
          | 'Sunset'
          | 'SunSnow'
          | 'Superscript'
          | 'SwatchBook'
          | 'SwissFranc'
          | 'SwitchCamera'
          | 'Sword'
          | 'Swords'
          | 'Syringe'
          | 'Table'
          | 'Table2'
          | 'TableCellsMerge'
          | 'TableCellsSplit'
          | 'TableColumnsSplit'
          | 'TableOfContents'
          | 'TableProperties'
          | 'TableRowsSplit'
          | 'Tablet'
          | 'Tablets'
          | 'TabletSmartphone'
          | 'Tag'
          | 'Tags'
          | 'Tally1'
          | 'Tally2'
          | 'Tally3'
          | 'Tally4'
          | 'Tally5'
          | 'Tangent'
          | 'Target'
          | 'Telescope'
          | 'Tent'
          | 'TentTree'
          | 'Terminal'
          | 'TestTube'
          | 'TestTubeDiagonal'
          | 'TestTubes'
          | 'TextAlignCenter'
          | 'TextAlignEnd'
          | 'TextAlignJustify'
          | 'TextAlignStart'
          | 'TextCursor'
          | 'TextCursorInput'
          | 'TextInitial'
          | 'TextQuote'
          | 'TextSearch'
          | 'TextSelect'
          | 'TextWrap'
          | 'Theater'
          | 'Thermometer'
          | 'ThermometerSnowflake'
          | 'ThermometerSun'
          | 'ThumbsDown'
          | 'ThumbsUp'
          | 'Ticket'
          | 'TicketCheck'
          | 'TicketMinus'
          | 'TicketPercent'
          | 'TicketPlus'
          | 'Tickets'
          | 'TicketSlash'
          | 'TicketsPlane'
          | 'TicketX'
          | 'Timer'
          | 'TimerOff'
          | 'TimerReset'
          | 'ToggleLeft'
          | 'ToggleRight'
          | 'Toilet'
          | 'Toolbox'
          | 'ToolCase'
          | 'Tornado'
          | 'Torus'
          | 'Touchpad'
          | 'TouchpadOff'
          | 'TowerControl'
          | 'ToyBrick'
          | 'Tractor'
          | 'TrafficCone'
          | 'TrainFront'
          | 'TrainFrontTunnel'
          | 'TrainTrack'
          | 'TramFront'
          | 'Transgender'
          | 'Trash'
          | 'Trash2'
          | 'TreeDeciduous'
          | 'TreePalm'
          | 'TreePine'
          | 'Trees'
          | 'Trello'
          | 'TrendingDown'
          | 'TrendingUp'
          | 'TrendingUpDown'
          | 'Triangle'
          | 'TriangleAlert'
          | 'TriangleDashed'
          | 'TriangleRight'
          | 'Trophy'
          | 'Truck'
          | 'TruckElectric'
          | 'TurkishLira'
          | 'Turntable'
          | 'Turtle'
          | 'Tv'
          | 'TvMinimal'
          | 'TvMinimalPlay'
          | 'Twitch'
          | 'Twitter'
          | 'Type'
          | 'TypeOutline'
          | 'Umbrella'
          | 'UmbrellaOff'
          | 'Underline'
          | 'Undo'
          | 'Undo2'
          | 'UndoDot'
          | 'UnfoldHorizontal'
          | 'UnfoldVertical'
          | 'Ungroup'
          | 'University'
          | 'Unlink'
          | 'Unlink2'
          | 'Unplug'
          | 'Upload'
          | 'Usb'
          | 'User'
          | 'UserCheck'
          | 'UserCog'
          | 'UserLock'
          | 'UserMinus'
          | 'UserPen'
          | 'UserPlus'
          | 'UserRound'
          | 'UserRoundCheck'
          | 'UserRoundCog'
          | 'UserRoundMinus'
          | 'UserRoundPen'
          | 'UserRoundPlus'
          | 'UserRoundSearch'
          | 'UserRoundX'
          | 'Users'
          | 'UserSearch'
          | 'UsersRound'
          | 'UserStar'
          | 'UserX'
          | 'Utensils'
          | 'UtensilsCrossed'
          | 'UtilityPole'
          | 'Van'
          | 'Variable'
          | 'Vault'
          | 'VectorSquare'
          | 'Vegan'
          | 'VenetianMask'
          | 'Venus'
          | 'VenusAndMars'
          | 'Vibrate'
          | 'VibrateOff'
          | 'Video'
          | 'VideoOff'
          | 'Videotape'
          | 'View'
          | 'Voicemail'
          | 'Volleyball'
          | 'Volume'
          | 'Volume1'
          | 'Volume2'
          | 'VolumeOff'
          | 'VolumeX'
          | 'Vote'
          | 'Wallet'
          | 'WalletCards'
          | 'WalletMinimal'
          | 'Wallpaper'
          | 'Wand'
          | 'WandSparkles'
          | 'Warehouse'
          | 'WashingMachine'
          | 'Watch'
          | 'Waves'
          | 'WavesArrowDown'
          | 'WavesArrowUp'
          | 'WavesLadder'
          | 'Waypoints'
          | 'Webcam'
          | 'Webhook'
          | 'WebhookOff'
          | 'Weight'
          | 'WeightTilde'
          | 'Wheat'
          | 'WheatOff'
          | 'WholeWord'
          | 'Wifi'
          | 'WifiCog'
          | 'WifiHigh'
          | 'WifiLow'
          | 'WifiOff'
          | 'WifiPen'
          | 'WifiSync'
          | 'WifiZero'
          | 'Wind'
          | 'WindArrowDown'
          | 'Wine'
          | 'WineOff'
          | 'Workflow'
          | 'Worm'
          | 'Wrench'
          | 'X'
          | 'Youtube'
          | 'Zap'
          | 'ZapOff'
          | 'ZoomIn'
          | 'ZoomOut'
        )
      | null;
    /**
     * Upload an SVG icon.
     */
    customSvg?: (number | null) | Media;
  };
  theme?: {
    /**
     * CSS color token for primary UI elements.
     */
    primaryColor?: string | null;
    /**
     * CSS color token for secondary UI elements.
     */
    secondaryColor?: string | null;
    /**
     * CSS color token for accents and highlights.
     */
    accentColor?: string | null;
    logo?: (number | null) | Media;
  };
  searchDefaults?: {
    /**
     * Placeholder text for the search input.
     */
    placeholder?: string | null;
    includeOlderVersions?: boolean | null;
    resultsLimit?: number | null;
  };
  /**
   * Automatically set to the newest published version for this service.
   */
  latestVersion?: (number | null) | DocVersion;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docVersions".
 */
export interface DocVersion {
  id: number;
  service: number | Service;
  /**
   * Semver string without a leading "v" (e.g. "1.2.3").
   */
  version: string;
  adminLabel?: string | null;
  /**
   * Doc page slug to use as the default landing page for this version.
   */
  defaultPageSlug: string;
  /**
   * Computed sortable key derived from the semver.
   */
  versionKey?: string | null;
  isPrerelease?: boolean | null;
  /**
   * Automatically derived from doc page statuses for this version.
   */
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docPageGroups".
 */
export interface DocPageGroup {
  id: number;
  service: number | Service;
  version: number | DocVersion;
  /**
   * Label used in the docs sidebar (e.g. "Getting Started").
   */
  name: string;
  /**
   * Auto-generated from the group name.
   */
  slug?: string | null;
  description?: string | null;
  /**
   * Manual uses the Order field. Auto uses Created At (oldest first, newest last).
   */
  orderMode: 'manual' | 'auto';
  /**
   * 1-based manual position. Example: 3 places this group as the third item.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docPages".
 */
export interface DocPage {
  id: number;
  service: number | Service;
  /**
   * Select a service first. Only versions for that service are available.
   */
  version: number | DocVersion;
  /**
   * Path segments for the page (lowercase kebab-case, use "/" for nested paths).
   */
  slug: string;
  /**
   * Optional sidebar group for this page.
   */
  group?: (number | null) | DocPageGroup;
  /**
   * Manual uses the Order field. Auto uses Created At (oldest first, newest last).
   */
  orderMode: 'manual' | 'auto';
  /**
   * 1-based manual position. Example: 3 places this page as the third item.
   */
  order?: number | null;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Incoming path to redirect (e.g. "/guides/old").
   */
  from: string;
  /**
   * Destination path or URL ("/..." or "https://...").
   */
  to: string;
  /**
   * Optional service scope for this redirect.
   */
  service?: (number | null) | Service;
  /**
   * Optional version scope. Select a service first.
   */
  version?: (number | null) | DocVersion;
  permanent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'docVersions';
        value: number | DocVersion;
      } | null)
    | ({
        relationTo: 'docPageGroups';
        value: number | DocPageGroup;
      } | null)
    | ({
        relationTo: 'docPages';
        value: number | DocPage;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?:
    | T
    | {
        source?: T;
        lucide?: T;
        customSvg?: T;
      };
  theme?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        accentColor?: T;
        logo?: T;
      };
  searchDefaults?:
    | T
    | {
        placeholder?: T;
        includeOlderVersions?: T;
        resultsLimit?: T;
      };
  latestVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docVersions_select".
 */
export interface DocVersionsSelect<T extends boolean = true> {
  service?: T;
  version?: T;
  adminLabel?: T;
  defaultPageSlug?: T;
  versionKey?: T;
  isPrerelease?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docPageGroups_select".
 */
export interface DocPageGroupsSelect<T extends boolean = true> {
  service?: T;
  version?: T;
  name?: T;
  slug?: T;
  description?: T;
  orderMode?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docPages_select".
 */
export interface DocPagesSelect<T extends boolean = true> {
  service?: T;
  version?: T;
  slug?: T;
  group?: T;
  orderMode?: T;
  order?: T;
  title?: T;
  content?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  service?: T;
  version?: T;
  permanent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docsSettings".
 */
export interface DocsSetting {
  id: number;
  /**
   * Optional title displayed on the landing page.
   */
  homeTitle?: string | null;
  /**
   * Optional description displayed on the landing page.
   */
  homeDescription?: string | null;
  /**
   * Landing page content shown at /.
   */
  homeContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docsSettings_select".
 */
export interface DocsSettingsSelect<T extends boolean = true> {
  homeTitle?: T;
  homeDescription?: T;
  homeContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}